import { Header, Pill } from "@/components/ui";
import { getJSON } from "@/lib/api";
type Detail={id:string;assessment:string;confidence:number;evidence_strength:string;rationale:string;gap:string;recommendation:string;citations:Array<{passage_id:string;document_name:string;locator:string;quote:string}>;verification:{valid:boolean;checks:Record<string,boolean>;issues:string[]};requirement:{reference:string;title:string;statement:string;source_quote:string};control:{code:string;title:string;objective:string;test_procedure:string;expected_evidence:string[]};human_review:null|{status:string;decision:string|null;reason:string|null;reviewer:string|null}};
export default async function Page({params}:{params:Promise<{id:string}>}){const {id}=await params;const d=await getJSON<Detail|null>(`/api/findings/${id}`,null);if(!d)return <p>Finding not found.</p>;return <><Header eyebrow="Decision explanation" title={`${d.requirement.reference} · ${d.control.code}`} description="A concise, source-grounded explanation of the assessment. Internal chain-of-thought is never displayed." action={<Pill value={d.assessment}/>}/>
  <div className="grid gap-5 xl:grid-cols-[1.4fr_1fr]"><div className="space-y-5"><section className="card p-6"><p className="eyebrow">Regulatory requirement</p><h2 className="mt-2 text-lg font-semibold">{d.requirement.title}</h2><p className="mt-3 text-sm leading-6 text-ink/70">{d.requirement.statement}</p><blockquote className="mt-4 rounded-xl border-l-4 border-amber bg-cream p-4 text-sm italic text-ink/60">“{d.requirement.source_quote}”</blockquote></section>
  <section className="card p-6"><p className="eyebrow">Mapped control</p><h2 className="mt-2 text-lg font-semibold">{d.control.title}</h2><p className="mt-3 text-sm text-ink/65">{d.control.objective}</p><div className="mt-4 rounded-xl bg-cream p-4"><p className="eyebrow">Test performed</p><p className="mt-2 text-sm">{d.control.test_procedure}</p></div></section>
  <section className="card p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Retrieved evidence</p><h2 className="mt-2 text-lg font-semibold">Cited passages</h2></div><Pill value={d.evidence_strength}/></div><div className="mt-5 space-y-3">{d.citations.map(c=><blockquote className="rounded-xl border border-ink/10 p-4" key={c.passage_id}><p className="text-sm leading-6">“{c.quote}”</p><footer className="mt-3 text-xs font-semibold text-moss">{c.document_name} · {c.locator}</footer></blockquote>)}{!d.citations.length&&<p className="text-sm text-ink/50">No trustworthy passages were available.</p>}</div></section></div>
  <aside className="space-y-5"><section className="card p-6"><p className="eyebrow">AI recommendation</p><div className="mt-3 flex items-end gap-3"><span className="text-4xl font-semibold">{(d.confidence*100).toFixed(0)}%</span><span className="pb-1 text-xs text-ink/50">confidence</span></div><p className="mt-5 text-sm leading-6">{d.rationale}</p>{d.gap&&<div className="mt-5 rounded-xl bg-rose-50 p-4"><p className="text-xs font-bold text-rose-800">GAP</p><p className="mt-1 text-sm text-rose-900">{d.gap}</p></div>}<div className="mt-4 rounded-xl bg-mint/60 p-4"><p className="text-xs font-bold text-moss">RECOMMENDATION</p><p className="mt-1 text-sm">{d.recommendation}</p></div></section>
  <section className="card p-6"><p className="eyebrow">Independent verification</p><div className="mt-4 space-y-3">{Object.entries(d.verification.checks||{}).map(([k,v])=><div className="flex justify-between gap-3 text-sm" key={k}><span>{k.replaceAll("_"," ")}</span><strong className={v?"text-emerald-700":"text-rose-700"}>{v?"Passed":"Failed"}</strong></div>)}</div></section>
  <section className="card p-6"><p className="eyebrow">Human review</p>{d.human_review?<><div className="mt-3"><Pill value={d.human_review.decision||d.human_review.status}/></div><p className="mt-3 text-sm">{d.human_review.reason||"Decision pending."}</p><p className="mt-2 text-xs text-ink/45">{d.human_review.reviewer||"Unassigned reviewer"}</p></>:<p className="mt-3 text-sm text-ink/50">Not queued.</p>}</section></aside></div></>}
